### ISSUE TITLE
配置数据库，使用HSQL

### ISSUE THREAD

**Issue by rieonke** [rieonke/bina#2]
1、引入HSQL依赖
```
<dependency>
	<groupId>org.hsqldb</groupId>
	<artifactId>hsqldb</artifactId>
	<scope>runtime</scope>
</dependency>
```
2、配置Spring
```
spring:
    datasource:
        url: jdbc:hsqldb:file:/path/to/db
        username: username
        password: password
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
    jpa:
      show-sql: true
```
3、可视化查看数据库，可以在IDEA中新建DBSource
